from django.core.management.base import BaseCommand
from properties.models import Property, PropertyType


class Command(BaseCommand):
    help = 'Create sample properties for testing'

    def handle(self, *args, **kwargs):
        # Create or get property types
        apartment_type, _ = PropertyType.objects.get_or_create(
            name='Apartment',
            defaults={'description': 'Multi-unit residential building'}
        )
        villa_type, _ = PropertyType.objects.get_or_create(
            name='Villa',
            defaults={'description': 'Luxury standalone house'}
        )
        house_type, _ = PropertyType.objects.get_or_create(
            name='House',
            defaults={'description': 'Residential house'}
        )

        # Sample properties data
        properties_data = [
            {
                'title': 'Luxury Family Home',
                'property_type': house_type,
                'listing_type': 'sale',
                'status': 'available',
                'address': '123 Main Street',
                'city': 'Mumbai',
                'state': 'Maharashtra',
                'zip_code': '400001',
                'location': 'Bandra West, Mumbai',
                'bedrooms': 4,
                'bathrooms': 3,
                'square_feet': 2500,
                'area': '2500',
                'parking_spaces': 2,
                'furnished_status': 'fully_furnished',
                'sale_price': 12500000,
                'price': '1,25,00,000',
                'has_pool': True,
                'has_garden': True,
                'description': 'Beautiful luxury family home with modern amenities. Features spacious rooms, contemporary design, and a large garden. Perfect for families looking for comfort and style.',
                'featured': True,
            },
            {
                'title': 'Skyper Pool Apartment',
                'property_type': apartment_type,
                'listing_type': 'sale',
                'status': 'available',
                'address': '456 High Rise Tower',
                'city': 'Mumbai',
                'state': 'Maharashtra',
                'zip_code': '400002',
                'location': 'Andheri East, Mumbai',
                'bedrooms': 3,
                'bathrooms': 2,
                'square_feet': 1800,
                'area': '1800',
                'parking_spaces': 1,
                'furnished_status': 'semi_furnished',
                'sale_price': 8500000,
                'price': '85,00,000',
                'has_pool': True,
                'has_garden': False,
                'description': 'Modern apartment with stunning skyline views. Building includes a rooftop pool, gym, and 24/7 security. Ideal for professionals and small families.',
                'featured': True,
            },
            {
                'title': 'North Dillard Street Villa',
                'property_type': villa_type,
                'listing_type': 'rent',
                'status': 'available',
                'address': '789 North Dillard Street',
                'city': 'Pune',
                'state': 'Maharashtra',
                'zip_code': '411001',
                'location': 'Koregaon Park, Pune',
                'bedrooms': 3,
                'bathrooms': 2,
                'square_feet': 2200,
                'area': '2200',
                'parking_spaces': 2,
                'furnished_status': 'fully_furnished',
                'rent_price': 75000,
                'price': '75,000',
                'has_pool': False,
                'has_garden': True,
                'description': 'Spacious villa in a premium location. Features modern interiors, private garden, and ample parking. Perfect for those seeking luxury living.',
                'featured': True,
            },
            {
                'title': 'Eaton Garth Penthouse',
                'property_type': apartment_type,
                'listing_type': 'sale',
                'status': 'available',
                'address': '321 Eaton Garth Complex',
                'city': 'Bangalore',
                'state': 'Karnataka',
                'zip_code': '560001',
                'location': 'Indiranagar, Bangalore',
                'bedrooms': 3,
                'bathrooms': 3,
                'square_feet': 2000,
                'area': '2000',
                'parking_spaces': 2,
                'furnished_status': 'fully_furnished',
                'sale_price': 9500000,
                'price': '95,00,000',
                'has_pool': False,
                'has_garden': False,
                'description': 'Stunning penthouse with panoramic city views. Premium finishes, spacious layout, and modern amenities. A perfect blend of luxury and comfort.',
                'featured': True,
            },
            {
                'title': 'New Apartment Nice View',
                'property_type': apartment_type,
                'listing_type': 'rent',
                'status': 'available',
                'address': '654 Lakeview Heights',
                'city': 'Hyderabad',
                'state': 'Telangana',
                'zip_code': '500001',
                'location': 'Hitech City, Hyderabad',
                'bedrooms': 2,
                'bathrooms': 2,
                'square_feet': 1400,
                'area': '1400',
                'parking_spaces': 1,
                'furnished_status': 'semi_furnished',
                'rent_price': 45000,
                'price': '45,000',
                'has_pool': False,
                'has_garden': False,
                'description': 'Cozy 2 BHK apartment with beautiful lake views. Well-maintained building with modern facilities. Great for working professionals.',
                'featured': False,
            },
            {
                'title': 'Diamond Manor Apartment',
                'property_type': apartment_type,
                'listing_type': 'sale',
                'status': 'available',
                'address': '987 Diamond Manor',
                'city': 'Chennai',
                'state': 'Tamil Nadu',
                'zip_code': '600001',
                'location': 'Anna Nagar, Chennai',
                'bedrooms': 3,
                'bathrooms': 2,
                'square_feet': 1650,
                'area': '1650',
                'parking_spaces': 1,
                'furnished_status': 'unfurnished',
                'sale_price': 7500000,
                'price': '75,00,000',
                'has_pool': False,
                'has_garden': False,
                'description': 'Well-designed 3 BHK apartment in a prime location. Excellent connectivity and near all major amenities. Great investment opportunity.',
                'featured': True,
            },
            {
                'title': 'Modern Studio Apartment',
                'property_type': apartment_type,
                'listing_type': 'rent',
                'status': 'available',
                'address': '147 Urban Center',
                'city': 'Delhi',
                'state': 'Delhi',
                'zip_code': '110001',
                'location': 'Hauz Khas, Delhi',
                'bedrooms': 1,
                'bathrooms': 1,
                'square_feet': 650,
                'area': '650',
                'parking_spaces': 1,
                'furnished_status': 'fully_furnished',
                'rent_price': 35000,
                'price': '35,000',
                'has_pool': False,
                'has_garden': False,
                'description': 'Compact and modern studio apartment. Perfect for singles or couples. Fully furnished with all modern amenities.',
                'featured': False,
            },
            {
                'title': 'Elegant Villa with Garden',
                'property_type': villa_type,
                'listing_type': 'sale',
                'status': 'available',
                'address': '258 Garden Estate',
                'city': 'Goa',
                'state': 'Goa',
                'zip_code': '403001',
                'location': 'Panaji, Goa',
                'bedrooms': 4,
                'bathrooms': 4,
                'square_feet': 3500,
                'area': '3500',
                'parking_spaces': 3,
                'furnished_status': 'semi_furnished',
                'sale_price': 18500000,
                'price': '1,85,00,000',
                'has_pool': True,
                'has_garden': True,
                'description': 'Magnificent villa with lush gardens and private pool. Spacious interiors, premium location, and serene surroundings. A dream home for luxury seekers.',
                'featured': True,
            },
            {
                'title': 'Contemporary Office Space',
                'property_type': apartment_type,
                'listing_type': 'rent',
                'status': 'available',
                'address': '369 Business Hub',
                'city': 'Noida',
                'state': 'Uttar Pradesh',
                'zip_code': '201301',
                'location': 'Sector 62, Noida',
                'bedrooms': 0,
                'bathrooms': 2,
                'square_feet': 1200,
                'area': '1200',
                'parking_spaces': 2,
                'furnished_status': 'unfurnished',
                'rent_price': 60000,
                'price': '60,000',
                'has_pool': False,
                'has_garden': False,
                'description': 'Modern office space in a prime business location. Excellent connectivity and infrastructure. Suitable for startups and small businesses.',
                'featured': False,
            },
        ]

        created_count = 0
        for prop_data in properties_data:
            property_obj, created = Property.objects.get_or_create(
                title=prop_data['title'],
                defaults=prop_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created property: {property_obj.title}'))
            else:
                self.stdout.write(self.style.WARNING(f'Property already exists: {property_obj.title}'))

        self.stdout.write(self.style.SUCCESS(f'\nTotal properties created: {created_count}'))
        self.stdout.write(self.style.SUCCESS(f'Total properties in database: {Property.objects.count()}'))
