# Generated by Django 4.2.7 on 2025-10-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
