# Generated by Django 4.2.7 on 2025-10-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0003_leadnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
