# Generated by Django 4.2.7 on 2025-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Real Estate CRM", max_length=200),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("about", models.TextField(blank=True)),
                ("policies", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, max_length=500, null=True, upload_to="company/"
                    ),
                ),
                (
                    "logo_url",
                    models.CharField(
                        blank=True,
                        help_text="URL for Cloudinary or external logo",
                        max_length=500,
                    ),
                ),
                ("additional_emails", models.JSONField(blank=True, default=list)),
                ("additional_phones", models.JSONField(blank=True, default=list)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("business_hours", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
    ]
