# Generated by Django 4.2.7 on 2025-10-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_companysettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companysettings",
            name="logo",
        ),
        migrations.AddField(
            model_name="companysettings",
            name="logo_public_id",
            field=models.CharField(
                blank=True,
                help_text="Cloudinary public_id for logo management",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="logo_url",
            field=models.CharField(
                blank=True, help_text="Cloudinary URL for company logo", max_length=500
            ),
        ),
    ]
