# Generated by Django 4.2.7 on 2025-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_remove_companysettings_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="offer_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
