# Generated by Django 4.2.7 on 2025-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_deal_offer_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("won", "Won"),
                    ("closed", "Closed"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
