# Generated by Django 4.2.7 on 2025-10-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Professional bio")),
                (
                    "specializations",
                    models.TextField(
                        blank=True, help_text="Comma-separated specializations"
                    ),
                ),
                ("years_experience", models.IntegerField(default=0)),
                (
                    "languages",
                    models.TextField(blank=True, help_text="Comma-separated languages"),
                ),
                ("office_location", models.CharField(blank=True, max_length=255)),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("certification", models.CharField(blank=True, max_length=255)),
                ("total_deals_closed", models.IntegerField(default=0)),
                ("total_leads_assigned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="accounts.employee",
                    ),
                ),
            ],
        ),
    ]
