# Generated by Django 4.2.7 on 2025-10-07 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "For Sale"), ("rent", "For Rent")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("location", models.CharField(max_length=200)),
                ("bedrooms", models.IntegerField(default=0)),
                ("bathrooms", models.IntegerField(default=0)),
                ("square_feet", models.IntegerField(default=0)),
                ("area", models.CharField(max_length=50)),
                ("parking_spaces", models.IntegerField(default=0)),
                (
                    "furnished_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi_furnished", "Semi Furnished"),
                            ("fully_furnished", "Fully Furnished"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "rent_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price", models.CharField(max_length=100)),
                ("has_pool", models.BooleanField(default=False)),
                ("has_garden", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("featured", models.BooleanField(default=False)),
                ("date_listed", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.IntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=250)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["-date_listed"],
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/")),
                ("title", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertytype",
            ),
        ),
    ]
