# Generated by Django 4.2.7 on 2025-10-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(max_length=500, upload_to="properties/"),
        ),
    ]
